### ISSUE TITLE
ModuleNotFoundError: No module named 'pyquery'

### ISSUE THREAD

**Issue by daidaiworm** [xiaoliang8006/SSR#1]
运行 python main.py
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from SSR_parse2 import parse
  File "I:\prj_python\ssr_parse\SSR-1-master\SSR_parse2.py", line 9, in <module>
    from LocateIP import LocateIP
  File "I:\prj_python\ssr_parse\SSR-1-master\LocateIP.py", line 9, in <module>
    from pyquery import PyQuery as pq
ModuleNotFoundError: No module named 'pyquery'

不能正常输出结果，哪里出问题了呢？

**Comment by daidaiworm** [comment]
安装了 pip install pyquery
问题解决
做个记录方便其他小白

**Comment by daidaiworm** [comment]
Traceback (most recent call last):
  File "main.py", line 30, in <module>
    ssr = temp[1][:-1]
IndexError: list index out of range

用自己的链接进行测试，结果直接报错。
